BusinessTrips/Models/DutyJourney.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace BusinessTrips.Models
{

    public class DutyJourney
    {
        /// <summary>
        /// Модель для работы с командировкой сотрудника
        /// </summary>
        /// 
        public int Id { get; set; }
        [Display(Name = "Цель коммандировки: ")]
        public string Point { get; set; }
        [Display(Name = "Рабочие дни: ")]
        public string WorkDay { get; set; }
        [Display(Name = "Выходные дни: ")]
        public string FreeDay { get; set; }
        [Display(Name = "Страна: ")]
        public string Country { get; set; }
        [Display(Name = "Город командировки: ")]
        public string City { get; set; }
        [Display(Name = "Дополнительно: ")]
        public string Additionally { get; set; }
        [Display(Name = "Начало командировки: ")]
        public DateTime BeginTrip { get; set; }
        [Display(Name = "Конец командировки: ")]
        public DateTime FinalTrip { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Hotel> Hotels { get; set; }
        public virtual ICollection<Passage> Passages { get; set; }

        public DutyJourney()
        {
            Employees = new List<Employee>();
            Passages = new List<Passage>();
            Hotels = new List<Hotel>();
        }
    }

}

BusinessTrips/Controllers/DutyJourneysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusinessTrips.Models;

namespace BusinessTrips.Controllers
{
    [Authorize(Users = "admin@mailSibCemAdmin.ru, kadr@mailSibCemKadr.ru")]
    public class DutyJourneysController : Controller
    {
        private BusinessTripsContext db = new BusinessTripsContext();

        [HttpPost]
        public ActionResult Search(string surname)
        {
            if (surname == "")
            {
                ViewBag.Message = "Некорректные данные для поиска!";
                return PartialView("Search");
            }

            var allEmpls = db.Employees.Where(a => a.Surname.Contains(surname)).ToList();

            if (allEmpls.Count <= 0)
            {
                ViewBag.Message = "Сотрудник с такой фамилией не найден!";
                return PartialView("Search");
            }




            var dutyJourneyListAll = from dj in db.DutyJourneys.ToList()
                                     join hotel in db.Hotels.ToList() on dj.Id equals hotel.DutyJourneyId
                                     join passage in db.Passeges.ToList() on hotel.DutyJourneyId equals passage.DutyJourneyId
                                     join empls in db.Employees on passage.DutyJourneyId equals empls.DutyJourneyId where empls.Surname == surname
                                     select new DutyJourney
                                     {
                                         Point = dj.Point,
                                         BeginTrip = dj.BeginTrip,
                                         FinalTrip = dj.FinalTrip,
                                         WorkDay = dj.WorkDay,
                                         FreeDay = dj.FreeDay,
                                         Country = dj.Country,
                                         City = dj.City,
                                         Additionally = dj.Additionally,
                                         Passages = dj.Passages,
                                         Hotels = dj.Hotels,
                                     };


            return PartialView("_Search", dutyJourneyListAll);

        }

        [Authorize(Users = "kadr@mailSibCemKadr.ru")]
        public ActionResult _Request()
        {
            var dutyJournes = db.DutyJourneys.Include(dj => dj.Employees).Include(dj => dj.Hotels).Include(dj => dj.Passages);
            return View(dutyJournes);
         
        }


        // GET: DutyJourneys
        public ActionResult Index()
        {
            
            return View(db.DutyJourneys.ToList());
        }

        // GET: DutyJourneys/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DutyJourneys/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Point,WorkDay,FreeDay,Country,City,Additionally,BeginTrip,FinalTrip")] DutyJourney dutyJourney)
        {
            if (ModelState.IsValid)
            {
                db.DutyJourneys.Add(dutyJourney);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dutyJourney);
        }

        // GET: DutyJourneys/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DutyJourney dutyJourney = db.DutyJourneys.Find(id);
            if (dutyJourney == null)
            {
                return HttpNotFound();
            }
            return View(dutyJourney);
        }

        // POST: DutyJourneys/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Point,WorkDay,FreeDay,Country,City,Additionally,BeginTrip,FinalTrip")] DutyJourney dutyJourney)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dutyJourney).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dutyJourney);
        }


        // GET: DutyJourneys/Delete/5
        [Authorize(Users = "admin@mailSibCemAdmin.ru")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DutyJourney dutyJourney = db.DutyJourneys.Find(id);
            if (dutyJourney == null)
            {
                return HttpNotFound();
            }
            return View(dutyJourney);
        }

        // POST: DutyJourneys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "admin@mailSibCemAdmin.ru")]
        public ActionResult DeleteConfirmed(int id)
        {
            DutyJourney dutyJourney = db.DutyJourneys.Find(id);
            db.DutyJourneys.Remove(dutyJourney);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BusinessTrips/Views/DutyJourneys/Create.cshtml
@model BusinessTrips.Models.DutyJourney

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DutyJourney</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Point, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Point, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Point, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FreeDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FreeDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FreeDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Additionally, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Additionally, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Additionally, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BeginTrip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BeginTrip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BeginTrip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FinalTrip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FinalTrip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FinalTrip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BusinessTrips/Views/DutyJourneys/Delete.cshtml
@model BusinessTrips.Models.DutyJourney

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DutyJourney</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Point)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Point)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FreeDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FreeDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Additionally)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Additionally)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BeginTrip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeginTrip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinalTrip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinalTrip)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BusinessTrips/Views/DutyJourneys/Edit.cshtml
@model BusinessTrips.Models.DutyJourney

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Командировка</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Point, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Point, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Point, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorkDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorkDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FreeDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FreeDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FreeDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Additionally, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Additionally, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Additionally, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BeginTrip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BeginTrip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BeginTrip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FinalTrip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FinalTrip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FinalTrip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

BusinessTrips/Views/DutyJourneys/Index.cshtml
@model IEnumerable<BusinessTrips.Models.DutyJourney>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Point)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorkDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FreeDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Additionally)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BeginTrip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FinalTrip)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Point)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WorkDay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FreeDay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Additionally)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BeginTrip)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FinalTrip)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) 
            @if (User.IsInRole("Admin")) {
                Html.ActionLink("Delete", "Delete", new { id = item.Id });
            }
        </td>
    </tr>
}

</table>

BusinessTrips/Views/DutyJourneys/_Request.cshtml
@model IEnumerable<BusinessTrips.Models.DutyJourney>
@Scripts.Render("~/scripts/jquery-1.10.2.min.js")
@Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")

@{
    ViewBag.Title = "_Request";
}

<p style="margin-top:50px">
    <h2>Страница поиска сотрудника: </h2>
</p>

@Html.Partial("_SearchEmplForm")

BusinessTrips/Views/DutyJourneys/_Search.cshtml
@model IEnumerable<BusinessTrips.Models.DutyJourney>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Point)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorkDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FreeDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Additionally)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BeginTrip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FinalTrip)
        </th>
        <th>
            Транспорт:
        </th>
        <th>
            Дата выезда:
        </th>
        <th>
            Город отеля:
        </th>
        <th>
            Название отеля:
        </th>
        <th>
            Дата заселения:
        </th>
        <th>
            Дата выселения:
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Point)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WorkDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FreeDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Additionally)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BeginTrip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinalTrip)
            </td>
            @foreach (var passage in item.Passages)
            {
                <td>
                    @passage.Transport
                </td>
                <td>
                    @passage.DateofDeparture
                </td>
            }
            @foreach(var hotel in item.Hotels) { 
            <td>
                @hotel.City
            </td>
            <td>
                @hotel.Name
            </td>
            <td>
                @hotel.DateIn
            </td>
            <td>
                @hotel.DateEnd
            </td>
            }
        </tr>
    }

</table>

BusinessTrips/Views/DutyJourneys/_SearchEmplForm.cshtml
<div class="container">
    <div style="margin-top: 20px" class="col-md-6">
        @using (Ajax.BeginForm("Search", "DutyJourneys",
                                                    new AjaxOptions
                                                    {
                                                        InsertionMode = InsertionMode.Replace,
                                                        HttpMethod = "POST",
                                                        LoadingElementId = "loadingBar",
                                                        LoadingElementDuration = 1000,
                                                        UpdateTargetId = "resultSearch",
                                                    }))

        {
            //ajax-loader.gif
            <form class="form-group">
                <div class="form-group row">
                    <label class="form-control-label" for="text">Введите фамилию сотрудника, которого хотите найти: </label>
                    <input id="text" type="text" name="surname" placeholder="Имя" class="form-control" />
                </div>
                <div class="form-group row">
                    <button type="submit" class="btn btn-primary">Search</button>
                    <img id="loadingBar" src="@Url.Content("../Content/loading2.gif")" style="display:none" />
                </div>
            </form>
            <div id="resultSearch"></div>
        }

    </div>
</div>